# Generated by Django 3.1.4 on 2020-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='djangoブログ', max_length=250),
        ),
    ]
